#!/bin/bash
: <<COMMENT
This script is used to install the required packages for yadm bootstrap

Available distro: Arch, Debian, Fedora, Ubuntu
Package:
- yadm
- git
- curl
- zsh
- neovim
- wget
- tmux
- vim plugins required package

Plugin
- oh-my-zsh
- zsh-autosuggestions
- zsh-syntax-highlighting
- zsh-completions
- powerlevel10k
- linux_config
- oh-my-tmux
COMMENT

PACKAGES=(
	"zsh"
	"git"
	"curl"
	"neovim"
	"wget"
	"tmux"
	"fzf"
	"ripgrep"
	"clang"
	"gcc"
	"nodejs"
	"npm"
	"luarocks"
	"yarn"
	"s-tui"
)

DEFAULT_ZSH="$HOME/.oh-my-zsh" # oh-my-zsh default path

ZSH=$DEFAULT_ZSH
ZSH_CUSTOM="$ZSH/custom" # oh-my-zsh custom path

function install_yay(){
	sudo pacman -S --noconfirm base-devel
	git clone https://aur.archlinux.org/yay.git
	cd yay
	makepkg -si --noconfirm
}

function install_required_packages() {
	distro=$(cat /etc/os-release | grep -w "ID" | cut -d "=" -f 2 | tr -d '"')
	case $distro in
	"arch")
		sudo pacman -Syu --noconfirm
		sudo pacman -S --noconfirm ${PACKAGES[@]}

		# Extra packages
		install_yay
		sudo pacman -S --noconfirm lua51 rustup cargo rust-analyzer hyprland hyprpaper swaylock waybar nwg-{look,displays,dock-hyprland} gnome-keyring
		rustup install stable
		;;
    "msys2")
		pacman -Syu --noconfirm
		pacman -S --noconfirm ${PACKAGES[@]}
        ;;
	"debian" | "ubuntu")
		sudo apt update
		sudo apt install -y ${PACKAGES[@]}
		;;
	"fedora")
		sudo dnf update -y
		sudo dnf install -y ${PACKAGES[@]}
		;;
	*)
		echo "Unsupported distro"
		exit 1
		;;
	esac
}

function install_oh_my_zsh() {
	unset ZSH
	sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended --keep-zshrc"
	ZSH=$DEFAULT_ZSH
}
function install_zsh_autosuggestions() {
	git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
}

function install_zsh_syntax_highlighting() {
	git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
}

function install_zsh_completions() {
	git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions
}

function install_powerlevel10k() {
	git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$ZSH/custom}/themes/powerlevel10k
}
function install_linux_config() {
	yadm submodule update --init --remote
	sh ~/.dotfiles/scripts/install.sh
}
function install_plugin() {
	install_oh_my_zsh
	install_zsh_autosuggestions
	install_zsh_syntax_highlighting
	install_zsh_completions
	install_powerlevel10k
	install_linux_config
}

function main() {
	install_required_packages
	# using zsh as default shell to install plugin
	install_plugin
}

main
echo "Done"
