unbind = $mainMod Shift, F

bindd=$mainMod Shift, f , maximize window, fullscreen, 1
bindd=$mainMod, f, $d toggle pin on focused window, exec, hyde-shell window.pin
bindd=ALT, SPACE, $d application finder , exec, pkill -x rofi || $rofi-launch d

# bindd=Control Shift, A, $d random wallpaper, exec, hyde-shell wallpaper -g --random
bindd=$mainMod, D, $d toggle show desktop, exec, $HOME/.config/hypr/custom/scripts/toggle-show-desktop.sh
# bindd=SUPER, $d start menu, exec, pkill -x rofi || $rofi-launch d
