unbind = $mainMod Shift, F

bindd=$mainMod Shift, f , maximize window, fullscreen, 1
bindd=$mainMod, f, $d toggle pin on focused window, exec, hyde-shell window.pin
bindd=ALT, SPACE, $d application finder , exec, pkill -x rofi || $rofi-launch d


